version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/CodePipelineJava
hooks:
  BeforeInstall:
    - location: scripts/clean_up_old_versions.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu